- hosts: all
  become: yes
  tasks:
    - name: Install prerequisites
      apt:
        name: 
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
        state: present
        update_cache: yes

    - name: Add Docker GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
        state: present

    - name: Install Docker CE
      apt:
        name: docker-ce
        state: latest
        update_cache: yes

    - name: Ensure Docker service is running
      service:
        name: docker
        state: started
        enabled: true

    - name: Copy application code
      copy:
        src: ./app/
        dest: /home/ubuntu/app/
        owner: ubuntu
        group: ubuntu
        mode: 0755

    - name: Build Docker image for app
      docker_image:
        path: /home/ubuntu/app
        name: paper-social

    - name: Run app container
      docker_container:
        name: app
        image: paper-social
        state: started
        ports:
          - "80:3000"
