- hosts: all
  become: yes
  tasks:
    - name: Install Docker
      apt:
        name: docker.io
        state: present
        update_cache: true
    - name: Run app container
      docker_container:
        name: app
        image: paper-social
        ports:
          - "80:3000"
