# GitHub Actions CI/CD pipeline
name: Deploy to Multi-Cloud

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Docker using official Docker script
      run: |
        curl -fsSL https://get.docker.com -o get-docker.sh
        sudo sh get-docker.sh

    - name: Build Docker image
      run: docker build -t paper-social ./app
